sudo: required
language: node_js
node_js:
  - "6"

services:
  - docker

before_install:
- docker pull localstack/localstack
- docker run -d -e SERVICES='sqs,sns' -p 127.0.0.1:4575:4575 -p 127.0.0.1:4576:4576 localstack/localstack
- docker ps -a

cache:
  directories:
    - "node_modules"

