image: thorgate/python3.4-node6
pipelines:
  default:
    - step:
        script:
          - pip install localstack
          - npm install
          - ping localhost -t 5
          - npm run test
  # custom:
  #   deploy-runtime:
  #     - step:
  #         script:
  #         - ./build-runtime.sh
  #         - scp -i ~/.ssh/config gm-runtime.zip ubuntu@52.27.128.130:~/tmp 

